import type { Config } from 'tailwindcss'

export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#000000',
        'on-primary': '#ffffff',
        ink: '#000000',
        canvas: '#ffffff',
        'inverse-canvas': '#000000',
        'inverse-ink': '#ffffff',
        'on-inverse-soft': '#ffffff',
        hairline: '#e6e6e6',
        'hairline-soft': '#f1f1f1',
        'surface-soft': '#f7f7f5',
        'block-lime': '#dceeb1',
        'block-lilac': '#c5b0f4',
        'block-cream': '#f4ecd6',
        'block-pink': '#efd4d4',
        'block-mint': '#c8e6cd',
        'block-coral': '#f3c9b6',
        'block-navy': '#1f1d3d',
        'accent-magenta': '#ff3d8b',
        'semantic-success': '#1ea64a',
        'overlay-scrim': '#000000',
      },
      spacing: {
        'xxs': '4px',
        'hair': '1px',
        'xs': '8px',
        'sm': '12px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'xxl': '48px',
        'section': '96px',
      },
      borderRadius: {
        'xs': '2px',
        'sm': '6px',
        'md': '8px',
        'lg': '24px',
        'xl': '32px',
        'pill': '50px',
      },
      fontFamily: {
        sans: "figmaSans, 'Inter', 'Segoe UI', sans-serif",
        mono: "figmaMono, 'JetBrains Mono', 'Consolas', monospace",
      },
      fontSize: {
        'display-xl': ['86px', { lineHeight: '1.00', letterSpacing: '-1.72px', fontWeight: '340' }],
        'display-lg': ['64px', { lineHeight: '1.10', letterSpacing: '-0.96px', fontWeight: '340' }],
        'headline': ['26px', { lineHeight: '1.35', letterSpacing: '-0.26px', fontWeight: '540' }],
        'subhead': ['26px', { lineHeight: '1.35', letterSpacing: '-0.26px', fontWeight: '340' }],
        'card-title': ['24px', { lineHeight: '1.45', letterSpacing: '0px', fontWeight: '700' }],
        'body-lg': ['20px', { lineHeight: '1.40', letterSpacing: '-0.14px', fontWeight: '330' }],
        'body': ['18px', { lineHeight: '1.45', letterSpacing: '-0.26px', fontWeight: '320' }],
        'body-sm': ['16px', { lineHeight: '1.45', letterSpacing: '-0.14px', fontWeight: '330' }],
        'link': ['20px', { lineHeight: '1.40', letterSpacing: '-0.10px', fontWeight: '480' }],
        'button': ['20px', { lineHeight: '1.40', letterSpacing: '-0.10px', fontWeight: '480' }],
        'eyebrow': ['14px', { lineHeight: '1.40', letterSpacing: '0px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
} satisfies Config
